gang_authority_user_homepage:
    pattern:  /index
    defaults: { _controller: GangAuthorityUserBundle:Default:index }
gang_authority_homepage:
    pattern:  /
    defaults: { _controller: GangAuthorityUserBundle:Default:index }
gang_authority_user_stats:
    pattern: /stats
    defaults: { _controller: GangAuthorityUserBundle:Default:stats }
gang_authority_user_telechargement:
    pattern: /telechargement
    defaults: { _controller: GangAuthorityUserBundle:Default:telechargement }
gang_authority_user_profile:
    pattern: /profile
    defaults: { _controller: GangAuthorityUserBundle:Default:profile }
gang_authority_user_connexion:
    pattern: /connexion
    defaults: { _controller: GangAuthorityUserBundle:Default:connexion }
gang_authority_user_oubli:
    pattern: /oublimdp
    defaults: { _controller: GangAuthorityUserBundle:Default:oublimdp }
gang_authority_admin_homepage:
    pattern:  /admin/index
    defaults: { _controller: GangAuthorityUserBundle:Admin:index }
gang_authority_admin:
    pattern:  /admin/
    defaults: { _controller: GangAuthorityUserBundle:Admin:index }
gang_authority_admin_voirsignalements:
    pattern:  /admin/voirSignalements
    defaults: { _controller: GangAuthorityUserBundle:Admin:voirsignalements }
gang_authority_admin_bannir:
    pattern:  /admin/bannir
    defaults: { _controller: GangAuthorityUserBundle:Admin:bannir }
gang_authority_admin_voirbannir:
    pattern:  /admin/voirBannir/{idsignalement}/{idcompte}
    defaults: { _controller: GangAuthorityUserBundle:Admin:voirbannir }
gang_authority_user_signup:
    pattern: /signup
    defaults: { _controller: GangAuthorityUserBundle:Default:signup }
gang_authority_admin_mission:
    pattern: /admin/mission
    defaults: { _controller: GangAuthorityUserBundle:Admin:creermission }