<?php

namespace Proxies\__CG__\GangAuthority\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Joueur extends \GangAuthority\UserBundle\Entity\Joueur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idcompte', 'pseudo', 'email', 'mdp', 'pointautorite', 'nbmorts', 'nbtues', 'argent', 'nomgang', 'combattrecompteAttaquant', 'concernersignalement', 'construiretypebatiment', 'entrainertypesbire', 'realisermission', 'salt', 'isActive');
        }

        return array('__isInitialized__', 'idcompte', 'pseudo', 'email', 'mdp', 'pointautorite', 'nbmorts', 'nbtues', 'argent', 'nomgang', 'combattrecompteAttaquant', 'concernersignalement', 'construiretypebatiment', 'entrainertypesbire', 'realisermission', 'salt', 'isActive');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Joueur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcompte()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcompte();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcompte', array());

        return parent::getIdcompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', array($pseudo));

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', array());

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp($mdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', array($mdp));

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', array());

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointautorite($pointautorite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointautorite', array($pointautorite));

        return parent::setPointautorite($pointautorite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointautorite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointautorite', array());

        return parent::getPointautorite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbmorts($nbmorts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbmorts', array($nbmorts));

        return parent::setNbmorts($nbmorts);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbmorts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbmorts', array());

        return parent::getNbmorts();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbtues($nbtues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbtues', array($nbtues));

        return parent::setNbtues($nbtues);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbtues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbtues', array());

        return parent::getNbtues();
    }

    /**
     * {@inheritDoc}
     */
    public function setArgent($argent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArgent', array($argent));

        return parent::setArgent($argent);
    }

    /**
     * {@inheritDoc}
     */
    public function getArgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArgent', array());

        return parent::getArgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomgang($nomgang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomgang', array($nomgang));

        return parent::setNomgang($nomgang);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomgang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomgang', array());

        return parent::getNomgang();
    }

    /**
     * {@inheritDoc}
     */
    public function addCombattrecompteAttaquant(\GangAuthority\UserBundle\Entity\Joueur $combattrecompteAttaquant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCombattrecompteAttaquant', array($combattrecompteAttaquant));

        return parent::addCombattrecompteAttaquant($combattrecompteAttaquant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCombattrecompteAttaquant(\GangAuthority\UserBundle\Entity\Joueur $combattrecompteAttaquant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCombattrecompteAttaquant', array($combattrecompteAttaquant));

        return parent::removeCombattrecompteAttaquant($combattrecompteAttaquant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCombattrecompteAttaquant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCombattrecompteAttaquant', array());

        return parent::getCombattrecompteAttaquant();
    }

    /**
     * {@inheritDoc}
     */
    public function addConcernersignalement(\GangAuthority\UserBundle\Entity\Signalement $concernersignalement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConcernersignalement', array($concernersignalement));

        return parent::addConcernersignalement($concernersignalement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConcernersignalement(\GangAuthority\UserBundle\Entity\Signalement $concernersignalement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConcernersignalement', array($concernersignalement));

        return parent::removeConcernersignalement($concernersignalement);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcernersignalement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcernersignalement', array());

        return parent::getConcernersignalement();
    }

    /**
     * {@inheritDoc}
     */
    public function addConstruiretypebatiment(\GangAuthority\UserBundle\Entity\Typebatiment $construiretypebatiment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConstruiretypebatiment', array($construiretypebatiment));

        return parent::addConstruiretypebatiment($construiretypebatiment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConstruiretypebatiment(\GangAuthority\UserBundle\Entity\Typebatiment $construiretypebatiment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConstruiretypebatiment', array($construiretypebatiment));

        return parent::removeConstruiretypebatiment($construiretypebatiment);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstruiretypebatiment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstruiretypebatiment', array());

        return parent::getConstruiretypebatiment();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntrainertypesbire(\GangAuthority\UserBundle\Entity\Typesbire $entrainertypesbire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntrainertypesbire', array($entrainertypesbire));

        return parent::addEntrainertypesbire($entrainertypesbire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntrainertypesbire(\GangAuthority\UserBundle\Entity\Typesbire $entrainertypesbire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntrainertypesbire', array($entrainertypesbire));

        return parent::removeEntrainertypesbire($entrainertypesbire);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrainertypesbire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrainertypesbire', array());

        return parent::getEntrainertypesbire();
    }

    /**
     * {@inheritDoc}
     */
    public function addRealisermission(\GangAuthority\UserBundle\Entity\Mission $realisermission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRealisermission', array($realisermission));

        return parent::addRealisermission($realisermission);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRealisermission(\GangAuthority\UserBundle\Entity\Mission $realisermission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRealisermission', array($realisermission));

        return parent::removeRealisermission($realisermission);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealisermission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealisermission', array());

        return parent::getRealisermission();
    }

}
