parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: Gang_Authority
    database_user: Goomoonryong
    database_password: murim
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: bbd7cbaa1fdcc85c4b1cbc9fa1025b27aaa63ef1
    database_path: null
