gang_authority_user:
    resource: "@GangAuthorityUserBundle/Resources/config/routing.yml"
    prefix:   /
<<<<<<< HEAD
login:
    pattern:    /login
    defaults:    { _controller: GangAuthorityUserBundle:Security:login}

login_check:
    pattern:    /login_check

logout:
    pattern:    /logout
=======

>>>>>>> 28c7a3e175ce7a0327206ff1480d6522167ee133
