gang_authority_user:
    resource: "@GangAuthorityUserBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:    /login
    defaults:    { _controller: GangAuthorityUserBundle:Security:login}

login_check:
    pattern:    /login_check

logout:
    pattern:    /logout
    
admin_login:
    pattern:    /admin/login
    defaults:    { _controller: GangAuthorityUserBundle:Security:adminLogin}

admin_login_check:
    pattern:    /admin/login_check

admin_logout:
    pattern:    /admin/logout